In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

In [15]:
data1 = pd.read_csv("Data_Detailed/cctransactions.csv")
#data2 = pd.read_csv("prediction_test.csv")
data3 = pd.read_csv("finalresultanalysis.csv")
data4 = pd.read_csv("Data_Detailed/frauddata_detailed.csv")

In [16]:
data1.columns

Index(['Unnamed: 0', 'TRANSACTION_ID', 'TX_DATETIME', 'CUSTOMER_ID',
       'TERMINAL_ID', 'TX_AMOUNT', 'TX_TIME_SECONDS', 'TX_TIME_DAYS',
       'TX_FRAUD', 'TX_FRAUD_SCENARIO', 'TX_B_Impact', 'category', 'gender',
       'lat', 'long', 'job', 'is_fraud'],
      dtype='object')

In [4]:
data2

        Unnamed: 0  Actual  Pred_Prob  Final
0                0       0   0.017955      1
1                1       0   0.015444      1
2                2       0   0.009566      0
3                3       0   0.034386      1
4                4       0   0.000041      0
...            ...     ...        ...    ...
555714      555714       0   0.001941      0
555715      555715       0   0.003226      0
555716      555716       0   0.008294      0
555717      555717       0   0.000006      0
555718      555718       0   0.002907      0

[555719 rows x 4 columns]

In [5]:
data3

,Unnamed: 0,trans_date_trans_time,month,year,Actual,Pred_Prob,Final
0,0,2020-06-21 12:14:25,6,2020,0,0.017955,1
1,1,2020-06-21 12:14:33,6,2020,0,0.015444,1
2,2,2020-06-21 12:14:53,6,2020,0,0.009566,0
3,3,2020-06-21 12:15:15,6,2020,0,0.034386,1
4,4,2020-06-21 12:15:17,6,2020,0,0.000041,0
...,...,...,...,...,...,...,...
555714,555714,2020-12-31 23:59:07,12,2020,0,0.001941,0
555715,555715,2020-12-31 23:59:09,12,2020,0,0.003226,0
555716,555716,2020-12-31 23:59:15,12,2020,0,0.008294,0
555717,555717,2020-12-31 23:59:24,12,2020,0,0.000006,0
555718,555718,2020-12-31 23:59:34,12,2020,0,0.002907,0

In [13]:
data4.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [18]:
result = pd.concat([data1, data4,data3], axis=1, join='inner')

In [19]:
result.columns

Index(['Unnamed: 0', 'TRANSACTION_ID', 'TX_DATETIME', 'CUSTOMER_ID',
       'TERMINAL_ID', 'TX_AMOUNT', 'TX_TIME_SECONDS', 'TX_TIME_DAYS',
       'TX_FRAUD', 'TX_FRAUD_SCENARIO', 'TX_B_Impact', 'category', 'gender',
       'lat', 'long', 'job', 'is_fraud', 'Unnamed: 0', 'trans_date_trans_time',
       'cc_num', 'merchant', 'category', 'amt', 'first', 'last', 'gender',
       'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job',
       'dob', 'trans_num', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud',
       'Unnamed: 0', 'trans_date_trans_time', 'month', 'year', 'Actual',
       'Pred_Prob', 'Final'],
      dtype='object')

In [20]:
result.to_csv('cctransactions.csv')

In [21]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555719 entries, 0 to 555718
Data columns (total 47 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Unnamed: 0             56899 non-null   float64
 1   TRANSACTION_ID         56899 non-null   float64
 2   TX_DATETIME            284807 non-null  float64
 3   CUSTOMER_ID            56899 non-null   float64
 4   TERMINAL_ID            56899 non-null   float64
 5   TX_AMOUNT              341706 non-null  float64
 6   TX_TIME_SECONDS        56899 non-null   float64
 7   TX_TIME_DAYS           284807 non-null  float64
 8   TX_FRAUD               56899 non-null   float64
 9   TX_FRAUD_SCENARIO      56899 non-null   float64
 10  TX_B_Impact            284807 non-null  float64
 11  category               555719 non-null  object
 12  gender                 555719 non-null  object
 13  lat                    555719 non-null  float64
 14  long                   555719 non-null  float64
 15  job                    555719 non-null  object
 16  is_fraud               555719 non-null  int64
 17  Unnamed: 0             555719 non-null  int64
 18  trans_date_trans_time  555719 non-null  object
 19  cc_num                 555719 non-null  int64
 20  merchant               555719 non-null  object
 21  category               555719 non-null  object
 22  amt                    555719 non-null  float64
 23  first                  555719 non-null  object
 24  last                   555719 non-null  object
 25  gender                 555719 non-null  object
 26  street                 555719 non-null  object
 27  city                   555719 non-null  object
 28  state                  555719 non-null  object
 29  zip                    555719 non-null  int64
 30  lat                    555719 non-null  float64
 31  long                   555719 non-null  float64
 32  city_pop               555719 non-null  int64
 33  job                    555719 non-null  object
 34  dob                    555719 non-null  object
 35  trans_num              555719 non-null  object
 36  unix_time              555719 non-null  int64
 37  merch_lat              555719 non-null  float64
 38  merch_long             555719 non-null  float64
 39  is_fraud               555719 non-null  int64
 40  Unnamed: 0             555719 non-null  int64
 41  trans_date_trans_time  555719 non-null  object
 42  month                  555719 non-null  int64
 43  year                   555719 non-null  int64
 44  Actual                 555719 non-null  int64
 45  Pred_Prob              555719 non-null  float64
 46  Final                  555719 non-null  int64
dtypes: float64(19), int64(12), object(16)
memory usage: 199.3+ MB

In [ ]:
'TX_B_Impact', 'category', 'gender',
       'lat', 'long', 'job', 'is_fraud', 'Unnamed: 0', 'trans_date_trans_time',
       'cc_num', 'merchant', 'category', 'amt', 'first', 'last', 'gender',
       'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job',
       'dob', 'trans_num', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud',
       'Unnamed: 0', 'trans_date_trans_time', 'month', 'year', 'Actual',
       'Pred_Prob', 'Final'

In [ ]:
{"", Int64.Type}, {"TRANSACTION_ID", Int64.Type}, {"TX_DATETIME", type datetime}, {"CUSTOMER_ID", Int64.Type}, {"TERMINAL_ID", Int64.Type}, {"TX_AMOUNT", type number}, {"TX_TIME_SECONDS", Int64.Type}, {"TX_TIME_DAYS", Int64.Type}, {"TX_FRAUD", Int64.Type}, {"TX_FRAUD_SCENARIO", Int64.Type}, {'TX_B_Impact',Int64.Type}, {'trans_date_trans_time', type datetime}, {'category', type string}, {'gender ', type string}, {'lat', Int64.Type}, {'long', Int64.Type}, {'category', type string}, {'amt', type number}, {'merch_lat', type number}, {'merch_long', type number}, {'Actual', Int64.Type}, {'Pred_Prob', Int64.Type}, {'Final', Int64.Type}